=== aiverify-foundation/aiverify/aiverify-test-engine/aiverify_test_engine/utils/aiverify.testresult.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/aiverify.algorithm.testresult.schema.json",
  "title": "Algorithm Output Schema",
  "description": "AI Verify algorithm output schema",
  "type": "object",
  "properties": {
    "gid": {
      "description": "Unique global identifier for the plugin",
      "type": "string",
      "pattern": "^[a-zA-Z0-9][a-zA-Z0-9-._]*$",
      "minLength": 1,
      "maxLength": 128
    },
    "cid": {
      "description": "Unique identifier for the algorithm within the plugin",
      "type": "string",
      "pattern": "^[a-zA-Z0-9][a-zA-Z0-9-._]*$",
      "minLength": 1,
      "maxLength": 128
    },
    "version": {
      "description": "Algorithm version",
      "type": "string"
    },
    "startTime": {
      "description": "Start date time of test",
      "type": "string",
      "format": "date-time"
    },
    "timeTaken": {
      "description": "Time take to complete running the test in seconds.",
      "type": "number"
    },
    "testArguments": {
      "description": "Test arguments",
      "type": "object",
      "properties": {
        "testDataset": {
          "description": "URI of test dataset",
          "type": "string",
          "format": "uri"
        },
        "mode": {
          "description": "Mode of model used, upload for model file and api for model api",
          "type": "string",
          "enum": [
            "upload",
            "api"
          ]
        },
        "modelType": {
          "description": "AI model type",
          "type": "string",
          "enum": [
            "classification",
            "regression"
          ]
        },
        "groundTruthDataset": {
          "description": "URI of test dataset",
          "type": "string",
          "format": "uri"
        },
        "groundTruth": {
          "description": "Ground truth column name",
          "type": "string"
        },
        "algorithmArgs": {
          "description": "Argument provided to the algorithm for running the tests. Test arguments should be defined in input.schema.json under each algorithm",
          "$comment": "Algorithm implementation should validate the algorithmArgs according to input.schema.json"
        }
      },
      "if": {
        "properties": {
          "mode": {
            "const": "upload"
          }
        }
      },
      "then": {
        "modelFile": {
          "description": "URI of model file",
          "type": "string",
          "format": "uri"
        }
      },
      "else": {
        "$comment": "TODO: Add reference to model api configuration specs"
      },
      "required": [
        "testDataset",
        "mode",
        "modelType"
      ],
      "dependentRequired": {
        "groundTruthDataset": [
          "groundTruth"
        ]
      }
    },
    "output": {
      "description": "Output from algorithm running. Test output schema should be defined in output.schema.json under each algorithm",
      "$comment": "AI Verify API-GW and any module that reads the output should validate the output according to output.schema.json"
    },
    "artifacts": {
      "description": "List the test artifacts (e.g. images) produced by the algorithm, to be upload to API-GW",
      "type": "array",
      "items": {
        "description": "filenames of the artifacts",
        "type": "string"
      }
    }
  },
  "required": [
    "gid",
    "cid",
    "startTime",
    "timeTaken",
    "testArguments",
    "output"
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.veritas/widgets/veritastool-mock-data.json
{
    "gid": "aiverify.stock.veritas",
    "cid": "veritastool",
    "version": "2.0.0a2",
    "startTime": "2025-03-17T00:25:28.940227",
    "timeTaken": 0.0,
    "testArguments": {
        "testDataset": "file:///Users/timlrx/Documents/aiverify/stock-plugins/aiverify.stock.veritas/algorithms/veritastool/examples",
        "mode": "upload",
        "modelType": "classification",
        "groundTruthDataset": "file:///Users/timlrx/Documents/aiverify/stock-plugins/aiverify.stock.veritas/algorithms/veritastool/examples",
        "groundTruth": "",
        "algorithmArgs": {},
        "modelFile": "file:///Users/timlrx/Documents/aiverify/stock-plugins/aiverify.stock.veritas/algorithms/veritastool/examples"
    },
    "output": {
        "fairness": {
            "fairness_init": {
                "fair_metric_name_input": "log_loss_parity",
                "fair_metric_name": "Log-loss Parity",
                "perf_metric_name": "True Negative Rate",
                "protected_features": [
                    "isforeign",
                    "isfemale"
                ],
                "fair_threshold_input": 80.0,
                "fair_neutral_tolerance": 0.001,
                "fair_priority": "benefit",
                "fair_concern": "eligible",
                "fair_impact": "normal"
            },
            "perf_metric_values": {
                "Selection Rate": [
                    0.25,
                    0.0
                ],
                "Accuracy": [
                    0.4109,
                    0.00944003050842528
                ],
                "Balanced Accuracy": [
                    0.3328624278157524,
                    0.006896979000013697
                ],
                "Recall": [
                    0.4109,
                    0.00944003050842528
                ],
                "Precision": [
                    0.4109,
                    0.00944003050842528
                ],
                "F1 Score": [
                    0.41089999999999993,
                    0.009440030508425281
                ],
                "True Negative Rate": [
                    0.8036333333333333,
                    0.0031466768361417576
                ],
                "False Negative Rate": [
                    0.5891,
                    0.00944003050842527
                ],
                "Negative Predictive Value": [
                    0.8036333333333333,
                    0.0031466768361417576
                ],
                "ROC AUC Score": [
                    0.69387221,
                    0.005995418738646434
                ],
                "Log-loss": [
                    1.2479378604825395,
                    0.008961754713421295
                ]
            },
            "class_distribution": {
                "CN": 0.3734,
                "TN": 0.2476,
                "CR": 0.2277,
                "TR": 0.1513
            },
            "weighted_confusion_matrix": {
                "tp": 4109.0,
                "fp": 5891.0,
                "tn": 24109.0,
                "fn": 5891.0
            },
            "calibration_curve": null,
            "perf_dynamic": null,
            "correlation_matrix": null,
            "features": {
                "isforeign": {
                    "fair_threshold": 0.2524945906154434,
                    "privileged": [
                        [
                            0
                        ]
                    ],
                    "unprivileged": [
                        [
                            1
                        ]
                    ],
                    "feature_distribution": {
                        "privileged_group": 0.7088,
                        "unprivileged_group": 0.2912
                    },
                    "fair_metric_values": {
                        "Demographic Parity": [
                            0.0,
                            0.0
                        ],
                        "Equal Opportunity": [
                            -0.018148612110237383,
                            0.02114658142234319
                        ],
                        "False Positive Rate Parity": [
                            0.006049537370079128,
                            0.007048860474114399
                        ],
                        "True Negative Rate Parity": [
                            -0.006049537370079183,
                            0.007048860474114384
                        ],
                        "False Negative Rate Parity": [
                            0.01814861211023744,
                            0.021146581422343186
                        ],
                        "Positive Predictive Parity": [
                            -0.018148612110237383,
                            0.02114658142234319
                        ],
                        "Negative Predictive Parity": [
                            -0.006049537370079183,
                            0.007048860474114384
                        ],
                        "False Discovery Rate Parity": [
                            0.01814861211023744,
                            0.021146581422343186
                        ],
                        "False Omission Rate Parity": [
                            0.006049537370079128,
                            0.007048860474114399
                        ],
                        "Equalized Odds": [
                            -0.006049537370079128,
                            0.0070488604741143915
                        ],
                        "Negative Equalized Odds": [
                            0.006049537370079072,
                            0.007048860474114408
                        ],
                        "Calibration by Group": [
                            -0.006049537370079128,
                            0.0070488604741143915
                        ],
                        "AUC Parity": [
                            -0.02985263081490952,
                            0.015406452863969916
                        ],
                        "Log-loss Parity": [
                            0.04991446632787633,
                            0.023001070319140025
                        ],
                        "Mutual Information Independence": [
                            "NA",
                            "NA"
                        ],
                        "Mutual Information Separation": [
                            "NA",
                            "NA"
                        ],
                        "Mutual Information Sufficiency": [
                            "NA",
                            "NA"
                        ]
                    },
                    "fairness_conclusion": "fair",
                    "tradeoff": null,
                    "feature_importance": null
                },
                "isfemale": {
                    "fair_threshold": 0.2578566029681289,
                    "privileged": [
                        [
                            0
                        ]
                    ],
                    "unprivileged": [
                        [
                            1
                        ]
                    ],
                    "feature_distribution": {
                        "privileged_group": 0.5979,
                        "unprivileged_group": 0.4021
                    },
                    "fair_metric_values": {
                        "Demographic Parity": [
                            0.0,
                            0.0
                        ],
                        "Equal Opportunity": [
                            -0.06271269679308233,
                            0.021511837752332237
                        ],
                        "False Positive Rate Parity": [
                            0.020904232264360778,
                            0.00717061258411075
                        ],
                        "True Negative Rate Parity": [
                            -0.020904232264360778,
                            0.007170612584110752
                        ],
                        "False Negative Rate Parity": [
                            0.06271269679308233,
                            0.02151183775233225
                        ],
                        "Positive Predictive Parity": [
                            -0.06271269679308233,
                            0.021511837752332237
                        ],
                        "Negative Predictive Parity": [
                            -0.020904232264360778,
                            0.007170612584110752
                        ],
                        "False Discovery Rate Parity": [
                            0.06271269679308233,
                            0.02151183775233225
                        ],
                        "False Omission Rate Parity": [
                            0.020904232264360778,
                            0.00717061258411075
                        ],
                        "Equalized Odds": [
                            -0.020904232264360778,
                            0.007170612584110729
                        ],
                        "Negative Equalized Odds": [
                            0.020904232264360667,
                            0.007170612584110748
                        ],
                        "Calibration by Group": [
                            -0.020904232264360778,
                            0.007170612584110729
                        ],
                        "AUC Parity": [
                            -0.06833795669898446,
                            0.013437913796693105
                        ],
                        "Log-loss Parity": [
                            0.102823064805037,
                            0.020070261856636344
                        ],
