=== aiverify-foundation/aiverify/common/schemas/aiverify.inputBlock.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "/ai-verify.inputBlock.schema.json",
	"title": "Input Block Metadata Schema",
	"description": "AI Verify Input Block metadata schema",
	"type": "object",
	"properties": {
		"cid": {
			"description": "Unique identifier for the input block within the plugin",
			"type": "string",
			"pattern": "^[a-zA-Z0-9][a-zA-Z0-9-._]*$",
			"minLength": 1,
			"maxLength": 128
		},
		"name": {
			"description": "Input Block name",
			"type": "string",
			"minLength": 1,
			"maxLength": 256
		},
		"version": {
			"description": "Version of the input block, default to plugin version if not specificed",
			"type": "string",
			"minLength": 1,
			"maxLength": 256
		},
		"author": {
			"description": "Input block author",
			"type": "string",
			"minLength": 1,
			"maxLength": 256
		},
		"tags": {
			"description": "Input block tags, used for searching",
			"type": "array",
			"maxItems": 128,
			"items": {
				"type": "string",
				"minLength": 1,
				"maxLength": 128
			}
		},
		"description": {
			"description": "Input Block description",
			"type": "string",
			"maxLength": 4096
		},
		"group": {
			"description": "Input Block group",
			"type": "string",
			"minLength": 1,
			"maxLength": 256
		},
		"groupNumber": {
			"description": "Input Block group number, used to order blocks within a group",
			"type": "integer"
		},
		"width": {
			"description": "Width of Input Block dialog",
			"type": "string",
			"enum": [
				"xs",
				"sm",
				"md",
				"lg",
				"xl"
			],
			"default": "md"
		},
		"fullScreen": {
			"description": "Width of Input Block dialog",
			"type": "boolean"
		}
	},
	"required": [
		"cid",
		"name"
	]
}

=== aiverify-foundation/aiverify/third-party-plugins/ccs_plugins/ccs_process_checklist/inputs/accuracy.meta.json
{
  "cid": "accuracy",
  "name": "Accuracy (General Good Practice)",
  "description": "This input block consists of 6 process checklist questions that the user has to complete. The 6 questions pertain to 2 testable criterion: 1) Model Reliability 2) Model Reproducibility",
  "group": "CCS Process Checklists",   
  "width": "xl",   
  "groupNumber": 8
}

=== aiverify-foundation/aiverify/third-party-plugins/ccs_plugins/ccs_process_checklist/inputs/flexibility.meta.json
{
  "cid": "flexibility",
  "name": "Flexibility (Competition)",
  "description": "This input block consists of 8 process checklist questions that the user has to complete. The 8 questions pertain to 3 testable criteria: 1) Lack of interoperability 2) High switching cost 3) Anticompetitive bundling or tying",
  "group": "CCS Process Checklists",   
  "width": "xl",   
  "groupNumber": 3
}

=== aiverify-foundation/aiverify/stock-plugins/user_defined_files/third-party-plugins/cccs_plugins/cccs_process_checklist/inputs/accessibility.meta.json
{
  "cid": "accessibility",
  "name": "Accessibility (Competition)",
  "description": "This input block consists of 4 process checklist questions that the user has to complete. The 4 questions pertain to 2 testable criteria: 1) Restricting of essential inputs. 2) Restricting access of AI products and services.",
  "group": "CCCS Process Checklists",   
  "width": "xl",   
  "groupNumber": 2 
}

=== aiverify-foundation/aiverify/third-party-plugins/ccs_plugins/ccs_process_checklist/inputs/fairness.meta.json
{
  "cid": "fairness",
  "name": "Fairness (Competition/Consumer Protection)",
  "description": "This input block consists of 5 process checklist questions that the user has to complete. The 5 questions pertain to 2 testable criteria: 1) Discrimination against certain target groups 2) Favouring certain brands/products over others",
  "group": "CCS Process Checklists",   
  "width": "xl",   
  "groupNumber": 4
}

=== aiverify-foundation/aiverify/third-party-plugins/ccs_plugins/ccs_process_checklist/inputs/accessibility.meta.json
{
  "cid": "accessibility",
  "name": "Accessibility (Competition)",
  "description": "This input block consists of 5 process checklist questions that the user has to complete. The 5 questions pertain to 3 testable criteria: 1) Restricting access to essential inputs 2) Restricting access of AI products and services 3) Access to data.",
  "group": "CCS Process Checklists",   
  "width": "xl",   
  "groupNumber": 2 
}
