=== aiverify-foundation/aiverify/ai-verify-portal/config/ai-verify.plugin.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/ai-verify.plugin.schema.json",
  "title": "Plugin Metadata Schema",
  "description": "AI Verify plugin metadata schema",
  "type": "object",
  "properties": {
    "gid": {
      "description": "Unique global identififer for the plugin",
      "type": "string",
      "pattern": "^[a-zA-Z0-9][a-zA-Z0-9-._]*$",
      "minLength": 1,
      "maxLength": 128
    },
    "version": {
      "description": "Version of the plugin",
      "type": "string",
      "minLength": 1,
      "maxLength": 256
    },
    "name": {
      "description": "Plugin name",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "author": {
      "description": "Plugin author",
      "type": "string",
      "maxLength": 128
    },
    "description": {
      "description": "Plugin description",
      "type": "string",
      "maxLength": 256
    },
    "url": {
      "description": "URL of project page",
      "type": "string",
      "maxLength": 2048
    }
  },
  "required": ["gid", "version", "name"]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/algorithms/fairness_metrics_toolbox_for_classification/aiverify_fairness_metrics_toolbox_for_classification/plugin.meta.json
{
    "gid": "aiverify.stock.fairness_metrics_toolbox_for_classification",
    "version": "0.10.0",
    "name": "fairness metrics toolbox for classification",
    "author": "AI Verify",
    "description": "The Fairness Metrics Toolbox (FMT) for Classification contains a list of fairness metrics to measure how resources (e.g. opportunities, food, loan, medical help) are allocated among the demographic groups (e.g. married male, married female) given a set of sensitive feature(s) (e.g. gender, marital status). This plugin is developed for classification models."
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.veritas/plugin.meta.json
{
    "gid": "aiverify.stock.veritas",
    "version": "2.0.0a2",
    "name": "AI Verify Veritas",
    "author": "AI Verify",
    "description": "The purpose of this toolkit is to facilitate the adoption of Veritas Methodology on Fairness & Transparency Assessment and spur industry development. It will also benefit customers by improving the fairness and transparency of financial services delivered by AIDA systems."
}
