=== aiverify-foundation/aiverify/ai-verify-portal/config/ai-verify.widget.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/ai-verify.widget.schema.json",
  "title": "Widget Metadata Schema",
  "description": "AI Verify Widget metadata schema",
  "type": "object",
  "properties": {
    "cid": {
      "description": "Unique identififer for the widget within the plugin",
      "type": "string",
      "pattern": "^[a-zA-Z0-9][a-zA-Z0-9-._]*$",
      "minLength": 1,
      "maxLength": 128
    },
    "name": {
      "description": "Widget name",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "description": {
      "description": "Widget description",
      "type": "string",
      "maxLength": 256
    },
    "widgetSize": {
      "description": "Describe the widget size in terms of canvas grid units",
      "type": "object",
      "properties": {
        "minW": {
          "description": "Minimum widget width",
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "minH": {
          "description": "Minimum widget height",
          "type": "integer",
          "minimum": 1,
          "maximum": 36
        },
        "maxW": {
          "description": "Maximum widget width",
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "maxH": {
          "description": "Maximum widget height",
          "type": "integer",
          "minimum": 1,
          "maximum": 36
        }
      },
      "required": ["minW", "minH", "maxW", "maxH"]
    },
    "properties": {
      "description": "List of widget properties",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "description": "Property key",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "helper": {
            "description": "Helper text for the property",
            "type": "string",
            "maxLength": 128
          },
          "default": {
            "description": "Property default value",
            "type": "string",
            "maxLength": 128
          }
        },
        "required": ["key", "helper"]
      }
    },
    "tags": {
      "description": "Widget tags, used for searching",
      "type": "array",
      "maxItems": 128,
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      }
    },
    "dependencies": {
      "description": "Widget dependencies",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "gid": {
            "description": "GID of the dependency component plugin. If empty, assume component within same plugin.",
            "type": "string",
            "maxLength": 128
          },
          "cid": {
            "description": "CID of the dependency component",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "version": {
            "description": "Version of the component dependency required",
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          }
        },
        "required": ["cid"]
      }
    },
    "mockdata": {
      "description": "Sample data to be fed into the widget in canvas mode",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "description": "Type of sample data",
            "type": "string",
            "enum": ["Algorithm", "InputBlock"]
          },
          "gid": {
            "description": "GID of sample data for component dependency. If empty, assume GID of same plugin",
            "type": "string",
            "maxLength": 128
          },
          "cid": {
            "description": "CID of sample data for component dependency",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "datapath": {
            "description": "Path to the file containing sample data",
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          }
        },
        "required": ["type", "cid", "datapath"]
      }
    }
  },
  "required": ["cid", "name", "widgetSize"]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.veritas/widgets/overall_summary.meta.json
{
  "cid": "overall_summary",
  "widgetSize": {
    "minW": 12,
    "minH": 14,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Overall Summary",
  "description": "Summary of all the processs checklists responses",
  "dependencies": [
    {
      "cid": "generic_process_checklist"
    },
    {
      "cid": "fairness_process_checklist"
    }
  ],
  "mockdata": [
    {
      "type": "InputBlock",
      "cid": "generic_process_checklist",
      "datapath": "generic_process_checklist.sample.json"
    },
    {
      "type": "InputBlock",
      "cid": "fairness_process_checklist",
      "datapath": "fairness_process_checklist.sample.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/blur-samples.meta.json
{
  "cid": "blur-samples",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Blur samples",
  "description": "To generate sample images for blur corruptions",
  "dependencies": [
    {
      "cid": "aiverify_blur_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_blur_corruptions",
      "datapath": "blur-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/user_defined_files/third-party-plugins/cccs_plugins/cccs_explainability_2.0/widgets/global_explainability_chart.meta.json
{
  "cid": "global_explainability_chart",
  "widgetSize": {
    "minW": 12,
    "minH": 16,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Bar Chart (Technical)",
  "description": "To display the average SHAP values using a bar chart",
  "dependencies": [
    {
      "cid": "aiverify_shap_toolbox",
      "gid": "aiverify.stock.shap_toolbox"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_shap_toolbox",
      "datapath": "shap_toolbox.sample.json"
    }
  ],
  "properties": [
    {
      "key": "topNFeatures",
      "helper": "To show the top N features in the chart",
      "default": "20"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/environment-samples-snow.meta.json
{
  "cid": "environment-samples-snow",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Samples (Environment: Snow)",
  "description": "To generate sample images for environment corruptions (snow)",
  "dependencies": [
    {
      "cid": "aiverify_environment_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_environment_corruptions",
      "datapath": "environment-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/general-bar-chart.meta.json
{
  "cid": "general-bar-chart",
  "widgetSize": {
    "minW": 12,
    "minH": 10,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Bar Chart (General Corruptions)",
  "description": "To generate bar charts to visualise the accuracy results when general corruptions are applied",
  "dependencies": [
    {
      "cid": "aiverify_general_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_general_corruptions",
      "datapath": "general-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/widgets/summary_recommendation.meta.json
{
  "cid": "summary_recommendation",
  "widgetSize": {
    "minW": 6,
    "minH": 3,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Interpretation (Summary)",
  "description": "To provide interpretation and recommendations to the results",
  "dependencies": [
    {
      "cid": "fairness_tree"
    },
    {
      "cid": "fairness_metrics_toolbox_for_classification"
    }
  ],
  "mockdata": [
    {
      "type": "InputBlock",
      "cid": "fairness_tree",
      "datapath": "fairness_tree.sample.json"
    },
    {
      "type": "Algorithm",
      "cid": "fairness_metrics_toolbox_for_classification",
      "datapath": "fmt.output.sample.json" 
    }
  ]
}

=== aiverify-foundation/aiverify/cccs_plugins/cccs_explainability_2.0/widgets/global_explainability_chart.meta.json
{
  "cid": "global_explainability_chart",
  "widgetSize": {
    "minW": 12,
    "minH": 16,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Bar Chart (Technical)",
  "description": "To display the average SHAP values using a bar chart",
  "dependencies": [
    {
      "cid": "shap_toolbox"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "shap_toolbox",
      "datapath": "shap_toolbox.sample.json"
    }
  ],
  "properties": [
    {
      "key": "topNFeatures",
      "helper": "To show the top N features in the chart",
      "default": "20"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/environment-bar-chart.meta.json
{
  "cid": "environment-bar-chart",
  "widgetSize": {
    "minW": 12,
    "minH": 10,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Bar Chart (Environment Corruptions)",
  "description": "To generate bar charts to visualise the accuracy results when environment corruptions are applied",
  "dependencies": [
    {
      "cid": "aiverify_environment_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_environment_corruptions",
      "datapath": "environment-corruption-mock-data.json"
    }
  ]
}
