=== aiverify-foundation/aiverify/ai-verify-portal/config/ai-verify.widget.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/ai-verify.widget.schema.json",
  "title": "Widget Metadata Schema",
  "description": "AI Verify Widget metadata schema",
  "type": "object",
  "properties": {
    "cid": {
      "description": "Unique identififer for the widget within the plugin",
      "type": "string",
      "pattern": "^[a-zA-Z0-9][a-zA-Z0-9-._]*$",
      "minLength": 1,
      "maxLength": 128
    },
    "name": {
      "description": "Widget name",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "description": {
      "description": "Widget description",
      "type": "string",
      "maxLength": 256
    },
    "widgetSize": {
      "description": "Describe the widget size in terms of canvas grid units",
      "type": "object",
      "properties": {
        "minW": {
          "description": "Minimum widget width",
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "minH": {
          "description": "Minimum widget height",
          "type": "integer",
          "minimum": 1,
          "maximum": 36
        },
        "maxW": {
          "description": "Maximum widget width",
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "maxH": {
          "description": "Maximum widget height",
          "type": "integer",
          "minimum": 1,
          "maximum": 36
        }
      },
      "required": ["minW", "minH", "maxW", "maxH"]
    },
    "properties": {
      "description": "List of widget properties",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "description": "Property key",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "helper": {
            "description": "Helper text for the property",
            "type": "string",
            "maxLength": 128
          },
          "default": {
            "description": "Property default value",
            "type": "string",
            "maxLength": 128
          }
        },
        "required": ["key", "helper"]
      }
    },
    "tags": {
      "description": "Widget tags, used for searching",
      "type": "array",
      "maxItems": 128,
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      }
    },
    "dependencies": {
      "description": "Widget dependencies",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "gid": {
            "description": "GID of the dependency component plugin. If empty, assume component within same plugin.",
            "type": "string",
            "maxLength": 128
          },
          "cid": {
            "description": "CID of the dependency component",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "version": {
            "description": "Version of the component dependency required",
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          }
        },
        "required": ["cid"]
      }
    },
    "mockdata": {
      "description": "Sample data to be fed into the widget in canvas mode",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "description": "Type of sample data",
            "type": "string",
            "enum": ["Algorithm", "InputBlock"]
          },
          "gid": {
            "description": "GID of sample data for component dependency. If empty, assume GID of same plugin",
            "type": "string",
            "maxLength": 128
          },
          "cid": {
            "description": "CID of sample data for component dependency",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "datapath": {
            "description": "Path to the file containing sample data",
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          }
        },
        "required": ["type", "cid", "datapath"]
      }
    }
  },
  "required": ["cid", "name", "widgetSize"]
}

=== aiverify-foundation/aiverify/stock-plugins/user_defined_files/third-party-plugins/cccs_plugins/cccs_fairness_classification_2.0/widgets/summary_description.meta.json
{
  "cid": "summary_description",
  "widgetSize": {
    "minW": 6,
    "minH": 3,
    "maxW": 12,
    "maxH": 36
  },
  "description": "To provide an introduction to the Fairness Metrics Toolbox for Classification",
  "name": "Description (Summary)",
  "dependencies": [
    {
      "cid": "fairness_tree",
      "gid": "aiverify.stock.fairness_metrics_toolbox_for_classification"
    },
    {
      "cid": "fairness_metrics_toolbox_for_classification",
      "gid": "aiverify.stock.fairness_metrics_toolbox_for_classification"
    }
  ],
  "mockdata": [
    {
      "type": "InputBlock",
      "cid": "fairness_tree",
      "datapath": "fairness_tree.sample.json"
    },
    {
      "type": "Algorithm",
      "cid": "fairness_metrics_toolbox_for_classification",
      "datapath": "fmt.output.sample.json" 
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/digital-samples-contrastdown.meta.json
{
  "cid": "digital-samples-contrastdown",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Samples (Digital: Contrast Down)",
  "description": "To generate sample images for digital corruptions (contrast down)",
  "dependencies": [
    {
      "cid": "aiverify_digital_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_digital_corruptions",
      "datapath": "digital-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/blur-samples-vmotion.meta.json
{
  "cid": "blur-samples-vmotion",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Samples (Blur: Vertical Blur)",
  "description": "To generate sample images for blur corruptions (vertical motion blur)",
  "dependencies": [
    {
      "cid": "aiverify_blur_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_blur_corruptions",
      "datapath": "blur-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/user_defined_files/third-party-plugins/cccs_plugins/cccs_explainability_2.0/widgets/summary_global_exp_chart.meta.json
{
  "cid": "summary_global_exp_chart",
  "widgetSize": {
    "minW": 12,
    "minH": 12,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Bar Chart (Summary)",
  "description": "To generate bar chart, interpretation and recommendations for explainability testing",
  "dependencies": [
    {
      "cid": "aiverify_shap_toolbox",
      "gid": "aiverify.stock.shap_toolbox"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_shap_toolbox",
      "datapath": "shap_toolbox.sample.json"
    }
  ],
  "properties": [
    {
      "key": "topNFeatures",
      "helper": "To show the top N features in the chart",
      "default": "20"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/widgets/summary_description.meta.json
{
  "cid": "summary_description",
  "widgetSize": {
    "minW": 6,
    "minH": 3,
    "maxW": 12,
    "maxH": 36
  },
  "description": "To provide an introduction to the Fairness Metrics Toolbox for Classification",
  "name": "Description (Summary)",
  "dependencies": [
    {
      "cid": "fairness_tree"
    },
    {
      "cid": "fairness_metrics_toolbox_for_classification"
    }
  ],
  "mockdata": [
    {
      "type": "InputBlock",
      "cid": "fairness_tree",
      "datapath": "fairness_tree.sample.json"
    },
    {
      "type": "Algorithm",
      "cid": "fairness_metrics_toolbox_for_classification",
      "datapath": "fmt.output.sample.json" 
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/environment-line-chart.meta.json
{
  "cid": "environment-line-chart",
  "widgetSize": {
    "minW": 12,
    "minH": 10,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Line Chart (Environment Corruptions)",
  "description": "To generate line charts to visualise the accuracy results when environment corruptions (rain, fog and snow) are applied",
  "dependencies": [
    {
      "cid": "aiverify_environment_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_environment_corruptions",
      "datapath": "environment-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/blur-line-chart.meta.json
{
  "cid": "blur-line-chart",
  "widgetSize": {
    "minW": 12,
    "minH": 10,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Line Chart (Blur Corruptions)",
  "description": "To generate line charts to visualise the accuracy results when blur corruptions (defocus, gaussian, glass, horizontal motion, vertical motion and zoom blur) are applied",
  "dependencies": [
    {
      "cid": "aiverify_blur_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_blur_corruptions",
      "datapath": "blur-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/general-samples-snp.meta.json
{
  "cid": "general-samples-snp",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Samples (General: Salt and Pepper Noise)",
  "description": "To generate sample images for general corruptions (salt and pepper noise)",
  "dependencies": [
    {
      "cid": "aiverify_general_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_general_corruptions",
      "datapath": "general-corruption-mock-data.json"
    }
  ]
}
