=== aiverify-foundation/aiverify/ai-verify-portal/config/ai-verify.widget.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "/ai-verify.widget.schema.json",
  "title": "Widget Metadata Schema",
  "description": "AI Verify Widget metadata schema",
  "type": "object",
  "properties": {
    "cid": {
      "description": "Unique identififer for the widget within the plugin",
      "type": "string",
      "pattern": "^[a-zA-Z0-9][a-zA-Z0-9-._]*$",
      "minLength": 1,
      "maxLength": 128
    },
    "name": {
      "description": "Widget name",
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "description": {
      "description": "Widget description",
      "type": "string",
      "maxLength": 256
    },
    "widgetSize": {
      "description": "Describe the widget size in terms of canvas grid units",
      "type": "object",
      "properties": {
        "minW": {
          "description": "Minimum widget width",
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "minH": {
          "description": "Minimum widget height",
          "type": "integer",
          "minimum": 1,
          "maximum": 36
        },
        "maxW": {
          "description": "Maximum widget width",
          "type": "integer",
          "minimum": 1,
          "maximum": 12
        },
        "maxH": {
          "description": "Maximum widget height",
          "type": "integer",
          "minimum": 1,
          "maximum": 36
        }
      },
      "required": ["minW", "minH", "maxW", "maxH"]
    },
    "properties": {
      "description": "List of widget properties",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "description": "Property key",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "helper": {
            "description": "Helper text for the property",
            "type": "string",
            "maxLength": 128
          },
          "default": {
            "description": "Property default value",
            "type": "string",
            "maxLength": 128
          }
        },
        "required": ["key", "helper"]
      }
    },
    "tags": {
      "description": "Widget tags, used for searching",
      "type": "array",
      "maxItems": 128,
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      }
    },
    "dependencies": {
      "description": "Widget dependencies",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "gid": {
            "description": "GID of the dependency component plugin. If empty, assume component within same plugin.",
            "type": "string",
            "maxLength": 128
          },
          "cid": {
            "description": "CID of the dependency component",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "version": {
            "description": "Version of the component dependency required",
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          }
        },
        "required": ["cid"]
      }
    },
    "mockdata": {
      "description": "Sample data to be fed into the widget in canvas mode",
      "type": "array",
      "maxItems": 256,
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "description": "Type of sample data",
            "type": "string",
            "enum": ["Algorithm", "InputBlock"]
          },
          "gid": {
            "description": "GID of sample data for component dependency. If empty, assume GID of same plugin",
            "type": "string",
            "maxLength": 128
          },
          "cid": {
            "description": "CID of sample data for component dependency",
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "datapath": {
            "description": "Path to the file containing sample data",
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          }
        },
        "required": ["type", "cid", "datapath"]
      }
    }
  },
  "required": ["cid", "name", "widgetSize"]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/digital-samples.meta.json
{
  "cid": "digital-samples",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Digital corruption samples",
  "description": "To generate sample images for digital corruptions",
  "dependencies": [
    {
      "cid": "aiverify_digital_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_digital_corruptions",
      "datapath": "digital-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/digital-bar-chart.meta.json
{
  "cid": "digital-bar-chart",
  "widgetSize": {
    "minW": 12,
    "minH": 10,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Bar Chart (Digital Corruptions)",
  "description": "To generate bar charts to visualise the accuracy results when digital corruptions are applied",
  "dependencies": [
    {
      "cid": "aiverify_digital_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_digital_corruptions",
      "datapath": "digital-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.fairness-metrics-toolbox-for-classification/widgets/technical_metrics.meta.json
{
  "cid": "technical_metrics",
  "name": "Fairness Metrics (All)",
  "description": "To generate all fairness metrics",
  "widgetSize": {
    "minW": 12,
    "minH": 34,
    "maxW": 12,
    "maxH": 36
  },
  "dependencies": [
    {
      "cid": "fairness_metrics_toolbox_for_classification"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "fairness_metrics_toolbox_for_classification",
      "datapath": "fmt.output.sample.json" 
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/general-samples-poisson.meta.json
{
  "cid": "general-samples-poisson",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Samples (General: Poisson Noise)",
  "description": "To generate sample images for general corruptions (poisson noise)",
  "dependencies": [
    {
      "cid": "aiverify_general_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_general_corruptions",
      "datapath": "general-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.decorators/widgets/header1.meta.json
{
  "cid": "header1",
  "name": "Header 1",
  "tags": [
    "stock",
    "decorator",
    "header"
  ],
  "properties": [
    {
      "key": "heading1",
      "helper": "Enter the heading 1",
      "default": ""
    }
  ],
  "widgetSize": {
    "minW": 1,
    "minH": 2,
    "maxW": 12,
    "maxH": 36
  },
  "dependencies": [],
  "mockdata": []
}

=== aiverify-foundation/aiverify/stock-plugins/user_defined_files/third-party-plugins/cccs_plugins/cccs_fairness_classification_2.0/widgets/interpretation_selected_metrics.meta.json
{
  "cid": "interpretation_selected_metrics",
  "widgetSize": {
    "minW": 6,
    "minH": 4,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Interpretation (Selected)",
  "description": "To provide interpretation for the selected fairness metric(s) from the fairness tree",
  "dependencies": [
    {
      "cid": "fairness_tree",
      "gid": "aiverify.stock.fairness_metrics_toolbox_for_classification"
    },
    {
      "cid": "fairness_metrics_toolbox_for_classification",
      "gid": "aiverify.stock.fairness_metrics_toolbox_for_classification"
    }
  ],
  "mockdata": [
    {
      "type": "InputBlock",
      "cid": "fairness_tree",
      "datapath": "fairness_tree.sample.json"
    },
    {
      "type": "Algorithm",
      "cid": "fairness_metrics_toolbox_for_classification",
      "datapath": "fmt.output.sample.json" 
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.image-corruption-toolbox/widgets/digital-samples-brightdown.meta.json
{
  "cid": "digital-samples-brightdown",
  "widgetSize": {
    "minW": 8,
    "minH": 7,
    "maxW": 12,
    "maxH": 36
  },
  "name": "Samples (Digital: Brightness Down)",
  "description": "To generate sample images for digital corruptions (brightness down)",
  "dependencies": [
    {
      "cid": "aiverify_digital_corruptions"
    }
  ],
  "mockdata": [
    {
      "type": "Algorithm",
      "cid": "aiverify_digital_corruptions",
      "datapath": "digital-corruption-mock-data.json"
    }
  ]
}

=== aiverify-foundation/aiverify/stock-plugins/aiverify.stock.decorators/widgets/text1.meta.json
{
  "cid": "text1",
  "name": "Text",
  "tags": ["stock", "decorator", "text"],
  "properties": [
    {
      "key": "text",
      "helper": "Enter your text",
      "default": ""
    }
  ],
  "widgetSize": {
    "minW": 1,
    "minH": 1,
    "maxW": 12,
    "maxH": 36
  },
  "dependencies": [],
  "mockdata": []
}
